In [3]:
# import important library
import os
import cv2
#define datapath. By using this code we can get the video frame.
PATH=os.getcwd()
data_path=PATH+'/dataset1'
data_dir_list = os.listdir(data_path)
video_data_dict={} 
newpath = r'C:\Users\HP\Desktop\internship_jogging' 
if not os.path.exists(newpath):
    os.makedirs(newpath)
for classes in data_dir_list:
    print(classes)
   
    data_dir_list2=os.listdir(data_path+'/'+ classes)
    
   
    
    count=0
    i=0
    for j,video in  enumerate(data_dir_list2):
        video_data_dict[j]=[]
        vidcap = cv2.VideoCapture('video.avi')
      
        newpath = r'C:\Users\HP\Desktop\internship_%s'%(classes)+'/'+str(j) 
        if not os.path.exists(newpath):
            os.makedirs(newpath)
        success = True
        count=0
        while success:
            success,image = vidcap.read()
             
            name = newpath+'/'+str(count) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name,image)
            #print ('Read a new frame: ', success)
           
            count +=1
                

jogging
walking


In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import train_test_split
from imutils import paths
import numpy as np
import argparse
import imutils
import cv2
import os


In [6]:

USE_SKLEARN_PREPROCESSING='True'
if USE_SKLEARN_PREPROCESSING:
    # using sklearn for preprocessing
    from sklearn import preprocessing
    def image_to_feature_vector(image, size=(32, 32)):
# resize the image to a fixed size, then flatten the image into
# a list of raw pixel intensities
        return cv2.resize(image, size).flatten()
#by using final_app function we can get all images corresponding to different class and different videos.
    def final_app(classes):
        PATH=os.getcwd()
        data_path=PATH+'/internship_%s'%(classes)
        data_dir_list = os.listdir(data_path)
        img_data_dict={}
        for i in range(52):
            img_data_dict[i]=[]
        j=0
        
        for classes in data_dir_list:

            data_dir_list2=os.listdir(data_path+'/'+ classes)
            for img in data_dir_list2:
                input_img=cv2.imread(data_path + '/'+ classes +'/'+ img)
                if input_img is not None:
                        input_img_flatten=image_to_feature_vector(input_img,size=(32,32))
                        img_data_dict[j].append(input_img_flatten) 
            j=j+1
        return(img_data_dict)


img_jogging = final_app('jogging')
#converting image dict into numpy array
img_jogging = [np.array(img_jogging[i]) for i in range(0,52)]
img_walking = final_app('walking')
img_walking = [np.array(img_jogging[i]) for i in range(0,52)]





In [7]:
#print(img_walking)


In [8]:
import numpy as np
X=np.append(img_jogging,img_walking,axis=0)
X = np.mean(X,axis=1)
X

array([[135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586],
       [135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586],
       [135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586],
       ...,
       [135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586],
       [135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586],
       [135.50810811, 135.50810811, 135.50810811, ..., 117.65585586,
        117.65585586, 117.65585586]])

In [9]:
import numpy as np
#here i am representing jogging by 0 and walking by 1.
y_jogging=np.zeros([52])
y_walking = np.ones([52])
y = np.append(y_jogging,y_walking,axis=0)
y = np.reshape(y,(104,1))
final = np.append(X,y,axis = 1)
final.shape


(104, 3073)

In [10]:
# random shuffle
finbal = np.take(final,np.random.permutation(final.shape[0]),axis=0,out=final)
finbal.shape
X_final = finbal[:,:finbal.shape[1]-2]
y_final = finbal[:,finbal.shape[1]-1]

In [11]:
y_final

array([1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1.])

In [12]:
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.3, random_state=0)
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.fit_transform(X_test)
for k in range(1,10):
    knn = KNeighborsClassifier(n_neighbors=k,p=2,metric='minkowski')
    model=knn.fit(X_train_std, y_train)
    y_pred=model.predict(X_test_std)
    from sklearn import metrics
    print (metrics.accuracy_score(y_test, y_pred))


0.4375
0.5625
0.5625
0.5625
0.5625
0.5625
0.5625
0.5625
0.5625


In [13]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
y_test

array([1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.])